services:
    Backend\Modules\Pages\Domain\Page\Command\CopyPagesToOtherLocaleHandler:
        public: true
        tags:
            - { name: command_handler, handles: Backend\Modules\Pages\Domain\Page\Command\CopyPagesToOtherLocale }
